version: '3.8'
services:
    postgres:
     image: 'postgres:latest'
     environment:
       - POSTGRES_PASSWORD=vahe
     volumes:
      - ./face-data:/var/lib/postgresql/data  
    nginx:
      volumes:
       - ./nginx:/etc/nginx/conf.d
      depends_on:
        - back
        - front
      restart: always
      build:
        dockerfile: Dockerfile
        context: ./nginx
      ports:
        - "3050:80"
    back:
     build:
      dockerfile: Dockerfile
      context: ./Face-recognition-back
     volumes:
      - /app/node_modules
      - ./Face-recognition-back:/app
     environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=smart_brain
      - PGPASSWORD=vahe
      - PGPORT=5432
    front:
     stdin_open: true
     build:
       dockerfile: Dockerfile
       context: ./Face-recognition-front
     volumes:
       - /app/node_modules
       - ./Face-recognition-front:/app 
    pgadmin:
       image: dpage/pgadmin4
       restart: always
       environment:
           PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
           PGADMIN_DEFAULT_PASSWORD: admin
           PGADMIN_LISTEN_ADDRESS: 0.0.0.0
       ports:
          - "5050:80"
